
export const productData = {
    products: [
        {
            name: 'Long Sleeve Shirt',
            image: 'https://assets.mayoral.com/images/t_auto_img,f_auto,c_limit,w_960/v1707211010/24-03912-054-XL-1/vestido-tul-plisado-nina-nude-XL-1.jpg',
            price: 35.99,
            sale: true,
            discount_percentage: 10,
            price_with_discount: 32.39,
            options: ['green', 'white', 'yellow'],
        },
        {
            name: 'Jeans',
            image: 'https://assets.mayoral.com/images/t_auto_img,f_auto,c_limit,w_960/v1702644636/24-03912-054-XL-4/vestido-tul-plisado-nina-nude-XL-4.jpg',
            price: 49.99,
            discount_percentage: 20,
            price_with_discount: 39.99,
            stock: false,
            options: ['green', 'pink', 'yellow'],
        },
        {
            name: 'Long dress',
            image: 'https://assets.mayoral.com/images/t_auto_img,f_auto,c_limit,w_960/v1698611479/24-00320-050-XL-1/rebeca-bolero-better-cotton-nina-nude-XL-1.jpg',
            price: 59.99,
            sale: true,
            discount_percentage: 15,
            price_with_discount: 50.99,
            stock: true,
            options: ['xs', 's', 'xl'],
        },
        {
            name: 'Winter Coat',
            image: 'https://assets.mayoral.com/images/t_auto_img,f_auto,c_limit,w_960/v1707436820/24-06101-024-XL-1/blusa-popelin-chica-flamingo-XL-1.jpg',
            price: 89.99,
            discount_percentage: 25,
            stock: false,
            price_with_discount: 67.49,
            options: ['red', 'orange', 'green'],
        },
        {
            name: 'Dress',
            image: 'https://assets.mayoral.com/images/t_auto_img,f_auto,c_limit,w_960/v1698612900/24-03911-088-XL-1/vestido-estampado-abertura-espalda-nina-nude-XL-1.jpg',
            price: 45.99,
            discount_percentage: 10,
            price_with_discount: 41.39,
            stock: true,
            options: ['orange', 'blue', 'yellow'],
        },
        {
            name: 'T-Shirt',
            image: 'https://assets.mayoral.com/images/t_auto_img,f_auto,c_limit,w_960/v1700155625/24-03911-088-XL-2/vestido-estampado-abertura-espalda-nina-nude-XL-2.jpg',
            price: 19.99,
            discount_percentage: 5,
            price_with_discount: 18.99,
            options: ['red', 'orange', 'green'],
        },
        {
            name: 'Skirt',
            image: 'https://assets.mayoral.com/images/t_auto_img,f_auto,c_limit,w_960/v1704907061/24-03480-063-XL-1/gabardina-lazada-nina-arena-XL-1.jpg',
            price: 29.99,
            discount_percentage: 15,
            price_with_discount: 25.49,
            options: ['green', 'yellow'],
        },
        {
            name: 'Sweater',
            image: 'https://assets.mayoral.com/images/t_auto_img,f_auto,c_limit,w_960/v1702549988/24-03172-035-XL-1/blusa-popelin-better-cotton-nina-crudo-XL-1.jpg',
            price: 39.99,
            discount_percentage: 10,
            price_with_discount: 35.99,
            stock: false,
            options: ['blue', 'pink', 'yellow'],
        },
        {
            name: 'Summmer sweater',
            image: 'https://assets.mayoral.com/images/t_auto_img,f_auto,c_limit,w_960/v1698613090/24-06852-077-XL-1/mono-largo-plisado-chica-crudo-XL-1.jpg',
            price: 79.99,
            discount_percentage: 30,
            price_with_discount: 55.99,
            sale: true,
            stock: true,
            options: ['green', 'white', 'orange'],
        },
        {
            name: 'Shorts',
            image: 'https://assets.mayoral.com/images/t_auto_img,f_auto,c_limit,w_960/v1698612942/24-03953-030-XL-1/conjunto-2-piezas-tul-nina-malva-XL-1.jpg',
            price: 24.99,
            stock: true,
            discount_percentage: 10,
            price_with_discount: 22.49,
        },
        {
            name: 'Blouse',
            image: 'https://assets.mayoral.com/images/t_auto_img,f_auto,c_limit,w_960/v1700155784/24-03953-030-XL-2/conjunto-2-piezas-tul-nina-malva-XL-2.jpg',
            price: 34.99,
            sale: true,
            discount_percentage: 15,
            price_with_discount: 29.74,
        },
        {
            name: 'T-shirt',
            image: 'https://assets.mayoral.com/images/t_auto_img,f_auto,c_limit,w_960/v1698613102/24-06946-046-XL-1/vestido-plisado-chica-flamingo-XL-1.jpg',
            price: 49.99,
            discount_percentage: 20,
            price_with_discount: 39.99,
        },
        {
            name: 'Dress',
            image: 'https://assets.mayoral.com/images/t_auto_img,f_auto,c_limit,w_960/v1707436820/24-06101-024-XL-1/blusa-popelin-chica-flamingo-XL-1.jpg',
            price: 14.99,
            sale: true,
            discount_percentage: 0,
            price_with_discount: 14.99,
            options: ['pink', 'yellow'],
        },
        {
            name: 'Hoodie',
            image: 'https://assets.mayoral.com/images/t_auto_img,f_auto,c_limit,w_960/v1702644636/24-03912-054-XL-4/vestido-tul-plisado-nina-nude-XL-4.jpg',
            price: 55.99,
            discount_percentage: 25,
            price_with_discount: 41.99,
            options: ['red', 'orange', 'green'],
        },
        {
            name: 'Scarf',
            image: 'https://assets.mayoral.com/images/t_auto_img,f_auto,c_limit,w_960/v1707211010/24-03912-054-XL-1/vestido-tul-plisado-nina-nude-XL-1.jpg',
            price: 19.99,
            discount_percentage: 5,
            price_with_discount: 18.99,
            options: ['s', 'm', 'l'],
        },
        {
            name: 'Shirt',
            image: 'https://assets.mayoral.com/images/t_auto_img,f_auto,c_limit,w_960/v1698613054/24-06459-045-XL-1/cazadora-sarga-better-cotton-chica-crudo-XL-1.jpg',
            price: 129.99,
            discount_percentage: 30,
            price_with_discount: 90.99,
            options: ['pink', 'white', 'yellow'],
        },
        {
            name: 'Jeans',
            image: 'https://assets.mayoral.com/image/upload/c_crop,x_0.10,y_0.00,w_0.75,h_1.00/t_auto_img,f_auto,c_limit,w_1536/46_EXTRA_MINI_V24.jpg',
            price: 25.99,
            discount_percentage: 10,
            price_with_discount: 23.39,
        },
        {
            name: 'Tie',
            image: 'https://assets.mayoral.com/image/upload/c_crop,x_0.00,y_0.04,w_1.00,h_0.75/t_auto_img,f_auto,c_limit,w_1536/36_BABY_P24.jpg',
            price: 9.99,
            discount_percentage: 0,
            price_with_discount: 9.99,
        },
        {
            name: 'Socks',
            image: 'https://assets.mayoral.com/images/t_auto_img,f_auto,c_limit,w_750/v1702638185/24-01823-023-XL-4/vestido-con-cubrepanal-mikado-recien-nacido-nata-XL-4.jpg',
            price: 7.99,
            discount_percentage: 0,
            price_with_discount: 7.99,
            options: ['red', 'orange', 'green'],
        },
        {
            name: 'Sumemr dress',
            image: 'https://assets.mayoral.com/images/t_auto_img,f_auto,c_limit,w_960/v1698613054/24-06459-045-XL-1/cazadora-sarga-better-cotton-chica-crudo-XL-1.jpg',
            price: 15.99,
            discount_percentage: 10,
            price_with_discount: 14.39,
        },
        {
            name: 'Winter shirt',
            image: 'https://assets.mayoral.com/images/t_auto_img,f_auto,c_limit,w_960/v1707436820/24-06101-024-XL-1/blusa-popelin-chica-flamingo-XL-1.jpg',
            price: 39.99,
            discount_percentage: 15,
            price_with_discount: 33.99,
        },
    ],
};
